#pragma once

#include "Class.h"

#pragma push_macro("CreateFont")
#undef CreateFont

class Surface // CMatSystemSurface: CTier3AppSystem<IMatSystemSurface,0>, CTier2AppSystem<IMatSystemSurface,0>, CTier1AppSystem<IMatSystemSurface,0>, CTier0AppSystem<IMatSystemSurface>, CBaseAppSystem<IMatSystemSurface>, IMatSystemSurface, vgui::ISurface, IAppSystem, ISchemeSurface, IAppSystem, ILocalizeTextQuery
{
public:
	INCONSTRUCTIBLE(Surface);

	enum __vftable
	{
		// class IAppSystem
		Connect,
		Disconnect,
		QueryInterface,
		Init,
		Shutdown,
		GetDependencies,
		GetTier,
		Reconnect,
		IsSingleton,

		// class ISurface
		RunFrame,
		GetEmbeddedPanel,
		SetEmbeddedPanel,
		PushMakeCurrent,
		PopMakeCurrent,
		DrawSetColor,
		DrawSetColor2,
		DrawFilledRect,
		DrawFilledRectArray,
		DrawOutlinedRect,
		DrawLine,
		DrawPolyLine,
		DrawSetApparentDepth,
		DrawClearApparentDepth,
		DrawSetTextFont,
		DrawSetTextColor,
		DrawSetTextColor2,
		DrawSetTextPos,
		DrawGetTextPos,
		DrawPrintText,
		DrawUnicodeChar,
		DrawFlushText,
		CreateHTMlWindow,
		PaintHTMLWindow,
		DeleteHTMLWindow,
		DrawGetTextureId,
		DrawGetTextureFile,
		DrawSetTextureFile,
		DrawSetTextureRGBA,
		DrawSetTexture,
		DeleteTextureByID,
		DrawGetTextureSize,
		DrawTexturedRect,
		IsTextureIDValid,
		CreateNewTextureID,
		GetScreenSize,
		SetAsTopMost,
		BringToFront,
		SetForegroundWindow,
		SetPanelVisible,
		SetMinimized,
		IsMinimized,
		FlashWindow,
		SetTitle,
		SetAsToolBar,
		CreatePopup,
		SwapBuffers,
		Invalidate,
		SetCursor,
		IsCursorVisible,
		ApplyChanges,
		IsWithin,
		HasFocus,
		SupportsFeature,
		RestrictPaintToSinglePanel,
		SetModalPanel,
		GetModalPanel,
		UnlockCursor,
		LockCursor,
		SetTranslateExtendedKeys,
		GetTopmostPopup,
		SetTopLevelFocus,
		CreateFont,
		SetFontGlyphSet,
		AddCustomFontFile,
		GetFontTall,
		GetFontAscent,
		IsFontAdditive,
		GetCharABCwide,
		GetCharacterWidth,
		GetTextSize,
		GetNotifyPanel,
		SetNotifyIcon,
		PlaySound,
		GetPopupCount,
		GetPopup,
		ShouldPaintChildPanel,
		RecreateContext,
		AddPanel,
		ReleasePanel,
		MovePopupToFront,
		MovePopupToBack,
		SolveTraverse,
		PaintTraverse,
		EnableMouseCapture,
		GetWorkspaceBounds,
		GetAbsoluteWindowBounds,
		GetProportionalBase,
		CalculateMouseVisible,
		NeedKBInput,
		HasCursorPosFunctions,
		SurfaceGetCursorPos,
		SurfaceSetCursorPos,
		DrawTexturedLine,
		DrawOutlinedCircle,
		DrawTexturedPolyLine,
		DrawTexturedSubRect,
		DrawTexturedPolygon,
		GetTitle,
		IsCursorLocked,
		SetWorkspaceInsets,
		DrawWordBubble,
		DrawGetUnicodeCharRenderInfo,
		DrawRenderCharFromInfo,
		DrawSetAlphaMultiplier,
		DrawGetAlphaMultiplier,
		SetAllowHTMLJavaScript,
		OnScreenSizeChanged,
		CreateCursorFromFile,
		DrawGetTextureMatInfoFactory,
		PaintTraverseEx,
		GetZPos,
		SetPanelForInput,
		DrawFilledRectFastFade,
		DrawFilledRectFade,
		DrawSetTextureRGBAEx,
		DrawSetTextScale,
		SetBitmapFontGlyphSet,
		AddBitmapFontFile,
		SetBitmapFontName,
		GetBitmapFontName,
		ClearTemporaryFontCache,
		GetIconImageForFullPath,
		DrawUnicodeString,
		PrecacheFontCharacters,
		GetFontName,
		ForceScreenSizeOverride,
		ForceScreenPosOffset,
		OffsetAbsPos,
		SetAbsPosForContext,
		GetAbsPosForContext,
		ResetFontCaches,
		IsScreenSizeOverrideActive,
		IsScreenPosOverrideActive,
		DestroyTextureID,
		GetTextureNumFrames,
		DrawSetTextureFrame,
		GetClipRect,
		SetClipRect,
		DrawTexturedRectEx,
		GetKernelCharWidth,
		DrawUpdateRegionTextureRGBA,
		BHTMLWindowNeedsPaint,
		DrawSetTextureRGBALinear,
		GetWebkitHTMLUserAgentString,
		Deprecated_AccessChromeHTMLController,

		// class IMatSystemSurface
		SetAppDrivesInput,
		EnableWindowMessages,
		Begin3DPaint,
		End3DPaint,
		DisableClipping,
		SetMouseCallbacks,
		InstallPlaySoundFunc,
		DrawColoredCircle,
		DrawColoredText,
		DrawColoredTextRect,
		DrawTextHeight,
		DrawTextLen,
		DrawPanelIn3DSpace,
		DrawSetTextureMaterial,
		HandleInputEvent,
		Set3DPaintTempRenderTarget,
		Reset3DPaintTempRenderTarget,
		DrawGetTextureMaterial,
		SetInputContext,
		DrawSetSubTextureRGBA,
		DrawTexturedSubRectGradient,
		__vftable = 179
	};

	VIRTUAL_METHOD(__vftable::DrawSetColor2, drawSetColor, __stdcall, void, (int r, int g, int b, int a), (this, r, g, b, a));
	VIRTUAL_METHOD(__vftable::UnlockCursor, unlockCursor, __stdcall, void, (), (this));
	VIRTUAL_METHOD(__vftable::LockCursor, lockCursor, __stdcall, void, (), (this));
};

#pragma pop_macro("CreateFont")